name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Trivy
      uses: aquasecurity/trivy-action@0.28.0

    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Create SBOM with Trivy
      run: |
        mkdir -p reports
        trivy sbom --format cyclonedx --output reports/sbom.json .

    - name: Trivy vulnerability scan (HTML)
      run: |
        trivy fs --format template --template "@contrib/html.tpl" --output reports/trivy-report.html .

    - name: Grype vulnerability scan (HTML via CycloneDX)
      run: |
        grype dir:. -o cyclonedx-json > reports/grype-sbom.json
        grype dir:. -o table > reports/grype-report.txt

    - name: Run tests (optional)
      run: |
        echo "Add your test suite here"
        # pytest or unittest

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        files: |
          reports/sbom.json
          reports/trivy-report.html
          reports/grype-sbom.json
          reports/grype-report.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload all reports as artifact
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: reports/
